version: "3.8"

services:
  web:
    build: .
    command: python labelmaker/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - migration
  migration:
    build: .
    command: python labelmaker/manage.py migrate